config/routes.rb
Map::Application.routes.draw do
  
  resources :users, :as => :directory_users do
    resource :mail, :password, :memberships, :mail_destination_inbox
  end
  resources :add_users do
    member do
      get 'resend_email'
    end
  end
  resources :groups, :as => :directory_groups
  
  resources :google_groups
  
  get 'logout' => 'application#logout'
  get 'search' => 'welcome#search'
  root :to => 'welcome#index'
  
end

app/controllers/mail_destination_inboxes_controller.rb
class MailDestinationInboxesController < ApplicationController
  
  before_filter :directory_user
  before_filter :google_apps_user
  
  def edit
    if @current_user.is?(@user) or @current_user.admin?(@user)
      @mail_destination = MailDestination.new(@user)
      render :edit
    else
      render :nothing => true, :status => 403
    end
  end
  
  def update
    if not (@current_user.is?(@user) or @current_user.admin?(@user))
      render :nothing => true, :status => 403 and return
    end
    
    @mail_destination = MailDestination.new(@user, params[:mail_destination])
    
    if @mail_destination.valid?
      old_destination_inbox = @user.mail_destination_inbox
      new_destination_inbox = @mail_destination.mail_destination_inbox == "true"
      
      if old_destination_inbox == new_destination_inbox
        flash[:message] = render_to_string :partial => 'no_change'
        redirect_to @user and return
      end
      destination_string = (@mail_destination.mail_destination_inbox == "true" && "inbox") || @user.mail_forward
      begin
        GoogleApps::Trollusk.connect { |t| t.only(@user.username, destination_string) } if @gapps_user
        @user.mail_destination_inbox = (@mail_destination.mail_destination_inbox == "true")
        Notify.mail_destination_inbox_update(@user, @current_user, @user.mail_forward).deliver
        flash[:message] = render_to_string :partial => 'updated'
        redirect_to @user
      rescue
        flash[:message] = render_to_string :partial => 'problem'
        redirect_to @user
      end
    else
      render :edit
    end
  end
  
end

app/views/mail_destination_inboxes/_no_change.html.erb
<p class="success">No change to inbox destination.</p>

app/views/mail_destination_inboxes/_problem.html.erb
<p class="errors">Unable to update inbox! Please contact <a href="mailto:admin@meet.mit.edu">admin@meet.mit.edu</a>.</p>

app/views/mail_destination_inboxes/_updated.html.erb
<p class="success">Inbox destination updated.</p>

<% if not @gapps_user %>
<p class="warnings">No Google Apps account. <b>Update will have no effect.</b></p>
<% end %>

app/views/mail_destination_inboxes/edit.html.erb
<% content_for :title, @user.name %>

<h1><%= image_tag('glyphish/40-inbox.png') %> Mail forwarding for <%= @user.name %></h1>
<h2><tt><%= @user.username %></tt></h2>

<%= form_for [ @user, @mail_destination ], :url => directory_user_mail_destination_inbox_path,
                               :html => { :method => :put,
                                          :onsubmit => String.new(update_page { |p| p.show('wait') }) } do |f| %>

<% if not @gapps_user %>
<p class="warnings">No Google Apps account. <b>This update will have no effect.</b></p>
<% end %>

<% if not @mail_destination.errors.empty? %>
<p class="errors">
<% @mail_destination.errors.each do |key, error| %>
<%= MailDestination.human_attribute_name(key) %> <%= error %><br/>
<% end %>
</p>
<% end %>

<div>
<%= f.radio_button :mail_destination_inbox, false %>
<%= f.label :mail_destination_inbox, content_tag(:span, 'Deliver email to your existing inbox at ') + content_tag(:tt, @user.mail_forward), :value => false, :class => 'widelabel' %><br/>
<%= f.radio_button :mail_destination_inbox, true %>
<%= f.label :mail_destination_inbox, 'Deliver email to a MEET Google Apps inbox', :value => true, :class => 'widelabel' %>
</div>

<%= f.submit :value => 'Update forwarding address', :disable_with => 'Updating forwarding address...' %>

<p id="wait" class="warnings" style="display:none">
The update will take up to a minute.<br/>
Pretty silly, I know. Please be patient.
</p>

<% end %>