config/routes.rb
Map::Application.routes.draw do
  
  resources :users, :as => :directory_users do
    resource :mail, :password, :memberships, :mail_destination_inbox
  end
  resources :add_users do
    member do
      get 'resend_email'
    end
  end
  resources :groups, :as => :directory_groups
  
  resources :google_groups
  
  get 'logout' => 'application#logout'
  get 'search' => 'welcome#search'
  root :to => 'welcome#index'
  
end

app/controllers/add_users_controller.rb
class AddUsersController < ApplicationController
  
  before_filter :authenticate_manager, :except => [ :show, :update ]
  skip_before_filter :authenticate, :only => [ :show, :update ]
  before_filter :unauthenticate, :only => [ :show, :update ]
  
  def new
    @user = Directory::NewUser.new
    @pending = Directory::NewUser.all
  end
  
  def create
    @user = Directory::NewUser.new(params[:directory_new_user].merge({
      :requester => @current_user
    }))
    @pending = Directory::NewUser.all
    if @user.valid_to_save?
      @user.save
      Notify.user_request(@user).deliver
      flash[:message] = render_to_string :partial => 'requested'
      redirect_to :root
    else
      render :new
    end
  end
  
  def show
    @user = Directory::NewUser.find_and_update(params[:id])
  end
  
  def update
    @user = Directory::NewUser.find_and_update(params[:id], params[:directory_new_user])
    if @user.valid_to_create?
      
      # Create local user
      @created = @user.create
      session[:username] = @created.username
      Notify.user_created(@created, @user.requester).deliver
      
      # Create Google user
      GoogleApps::User.new(
        :user_name => @created.username,
        :given_name => @created.first_name,
        :family_name => @created.last_name,
        :password => Password.random
      ).save
      GoogleApps::OrgUser.new(
        :org_user_email => "#{@created.username}@#{GoogleApps.connection.domain}",
        :org_unit_path => GoogleApps::ORG_UNIT_GROUPS[@user.primary_group]
      ).save
      
      # Add to Google group
      GoogleApps::Group.find(@user.primary_group).members.new(
        :member_id => @created.mail
      ).save
      
      redirect_to edit_directory_user_password_path(@created)
    else
      render :show
    end
  end
  
  def resend_email
    @user = Directory::NewUser.find_and_update(params[:id])
    Notify.user_request(@user).deliver
    redirect_to :root
  end

  private
    
    def authenticate_manager
      if not @current_user.manager?
        render :nothing => true, :status => 403
      end
    end
    
    def unauthenticate
      if session[:username]
        @error = 'Not a new user'
        render 'application/error', :status => 403
      end
    end
    
end

app/helpers/add_users_helper.rb
module AddUsersHelper
  
  def primary_groups
    GoogleApps::ORG_UNIT_GROUPS.keys.map { |groupname| Directory::Group.find(groupname) }
  end
  
end

app/views/add_users/_errors.html.erb
<% if not errors.empty? %>
<p class="errors">
<% errors.each do |key, error| %>
<%= Directory::NewUser.human_attribute_name(key) %> <%= error %><br/>
<% end %>
</p>
<% elsif not @user.warnings.empty? %>
<%= hidden_field :directory_new_user, :warned, :value => @user.warnings.keys.join(',') %>
<p class="warnings">
Warning: please double-check the following...<br/>
<% @user.warnings.each do |key, warning| %>
<%= Directory::NewUser.human_attribute_name(key) %> <%= warning %><br/>
<% end %>
</p>
<% end %>

app/views/add_users/_requested.html.erb
<p class="success">
Account request sent to <%= @user.mail_forward %>.<br/>
<%= @user.first_name %> should now follow the emailed directions.
</p>

app/views/add_users/new.html.erb
<% content_for :title, 'New user' %>

<h1>Add a new user</h1>

<% if ! @pending.empty? %>
<p class="success">
<%= pluralize @pending.size, 'new user' %> pending:<br/>
<% @pending.each do |user| %>
<%= "#{user.name}: <#{user.mail_forward}>" %>&nbsp;<%=link_to "Resend email", :action => "resend_email",:id => user.cn %>
<br/>
<% end %>
</p>
<% end %>

<%= form_for @user, :url => add_users_path do |f| %>

<%= render :partial => 'errors', :object => @user.save_errors %>

<div>
<%= image_tag('glyphish/111-user.png', :class => 'inline', :style => 'padding: 0 2px') %>
<%= f.label :first_name, :class => 'fallback' %>
<%= f.text_field :first_name, :placeholder => 'First name', :size => 15 %>
<%= f.label :last_name, :class => 'fallback' %>
<%= f.text_field :last_name, :placeholder => 'Last name', :size => 20 %>
</div>

<p>
If you provide a username, the user will be unable to choose their own username.
Leave blank if you would like the user to select his/her own username.
</p>

<div>
<%= image_tag('glyphish/111-user.png', :class => 'inline', :style => 'padding: 0 2px') %>
<%= f.label :username, :class => 'fallback' %>
<%= f.text_field :username, :placeholder => 'Username', :size => 15 %>
</div>

<div>
<%= image_tag('glyphish/18-envelope.png', :class => 'inline') %>
<%= f.label :mail_forward, 'Forwarding address', :class => 'fallback' %>
<%= f.email_field :mail_forward, :placeholder => 'Forwarding email address' %>
</div>

<div>
<%= image_tag('glyphish/112-group.png', :class => 'inline') %>
<%= f.label :primary_group %>
<%= f.select :primary_group, primary_groups.map {|g| [ g.name, g.groupname ] }, :include_blank => true %>
</div>

<%= f.submit :value => 'Send account creation email', :disable_with => 'Sending account creation email...' %>

<% end %>

app/views/add_users/show.html.erb
<% content_for :head do %>
<%= javascript_include_tag 'users' %>
<% end %>
<% content_for :title, 'New user' %>

<h1>Create a new user account</h1>

<%= form_for @user, :url => add_user_path do |f| %>

<h2>
<%= image_tag('glyphish/111-user.png', :class => 'inline') %>
New MEET account for: <%= @user.first_name %> <%= @user.last_name %>
</h2>

<p>
<%= image_tag('glyphish/18-envelope.png', :class => 'inline') %>
Your existing email address: <tt><%= @user.mail_forward %></tt>
</p>

<p>
<%= image_tag('glyphish/112-group.png', :class => 'inline') %>
Primary group: <%= Directory::Group.find(@user.primary_group).name %>
</p>

<%= render :partial => 'errors', :object => @user.errors %>

<div>
<b>Please select your username</b>, which will also be your email address <tt>@<%= Directory.connection.base_domain %></tt>.<br/>
The username must consist of lowercase alphabetic characters.<br/>
It should be based on your name and easy for others to identify as you.</br>
<%= f.label :username, :class => 'fallback' %>
<%= f.text_field :username, :placeholder => (@user.username or 'Username'), :disabled => (@user.username && !@user.username.empty?) %>
</div>

<div>
<b>Select where to receive your email</b> addressed to <tt><span id="username-preview"><%= @user.username %></span>@<%= Directory.connection.base_domain %></tt>:<br/>
<%= f.radio_button :mail_inbox, false, :disabled => true %><!-- BUG: fix Trollusk and enable -->
<%= f.label :mail_inbox, content_tag(:span, 'Deliver email to your existing inbox at ') + content_tag(:tt, @user.mail_forward), :value => false, :class => 'widelabel' %><br/>
<%= f.radio_button :mail_inbox, true %>
<%= f.label :mail_inbox, 'Deliver email to a MEET Google Apps inbox', :value => true, :class => 'widelabel' %>
</div>

<%= f.submit :value => 'Create account', :disable_with => 'Creating account...' %>

<% end %>