config/routes.rb
Map::Application.routes.draw do
  
  resources :users, :as => :directory_users do
    resource :mail, :password, :memberships, :mail_destination_inbox
  end
  resources :add_users do
    member do
      get 'resend_email'
    end
  end
  resources :groups, :as => :directory_groups
  
  resources :google_groups
  
  get 'logout' => 'application#logout'
  get 'search' => 'welcome#search'
  root :to => 'welcome#index'
  
end

app/views/notify/mail_destination_inbox_update.text.erb
<%= @user.first_name %>-

Your MEET email delivery settings have been updated.

<% if @user.mail_destination_inbox %>
Mail will now be delivered to your MEET GMail account at https://mail.meet.mit.edu.
<% else %>
Mail will now be forwarded to your forwarding address and will no longer be sent to your MEET GMail inbox.
<% end %>

<% if not @user.is?(@updater) %>
This change was made by <%= @updater.name %>.

<% end %>
If you think this was a mistake, please email: <%= message.reply_to %>

app/views/notify/mail_forward_update.text.erb
<%= @user.first_name %>-

Your MEET email forwarding address has been updated.

  New address: <%= @user.mail_forward %>

<% if not @user.is?(@updater) %>
This change was made by <%= @updater.name %>.

<% end %>
If you think this was a mistake, please email: <%= message.reply_to %>

app/views/notify/password_reset.text.erb
<%= @user.first_name %>-

Your MEET user account password has been reset.

  Username: <%= @user.username %>
  Temporary password: <%= @temporary.html_safe %>

To continue using your account, you must log in and set a new password:

  <%= directory_user_url(@user) %>

Your password was reset by <%= @resetter.name %>.

If you think this was a mistake, please email: <%= message.reply_to %>

app/views/notify/user_created.text.erb
<%= @user.first_name %>-

Welcome to MEET!

Your username is <%= @user.username %>, and your email address is <%= @user.mail %>.

Please follow up with <%= @requester.first_name %> to learn more about your account.

For technical questions and issues, please email: <%= message.reply_to %>

app/views/notify/user_request.text.erb
<%= @user.first_name %>-

Welcome to MEET!

To set up your MEET account, please follow the link below:

  <%= add_user_url(@user.to_key) %>

This account request was sent by <%= @user.requester.name %>.

If you think this was a mistake, please email: <%= message.reply_to %>